### ISSUE TITLE
Error Codes

### ISSUE THREAD

**Issue by StollD** [KSP-SpaceDock/SpaceDock-Backend#10]
Every error message we return _needs_ an unique error code. Otherwise the frontend has to use the error messages to determine the error, and that is just an utter pain to maintain.

**Comment by morganpdx** [comment]
Hi! I might be able to help with this.  Can you provide some more information about what you'd like to change/update?

**Comment by StollD** [comment]
Well, all error messages should return an error code in their return value. It has to be the same for errors that are roughly the same (all "mod id is invalid" for example).

So it is really just adding a new entry to the dictionary, choosing a random number, and documenting it somewhere

EDIT: Example: `return {'error': True, 'code': 10, 'reasons': ['The modid is invalid.']}, 400`

**Comment by morganpdx** [comment]
Excellent thanks!  I'll start working in it.  Any recommendations on where would be the most ideal place to document the codes?

**Comment by StollD** [comment]
Maybe a docs/ folder in the repository?

**Comment by morganpdx** [comment]
I greped the repo and made a quick csv of the error code numbering and categorization, if you want to take a quick look and see if that's gonna work
[errorlist.pdf](https://github.com/KSP-SpaceDock/SpaceDock-Backend/files/505202/errorlist.pdf)

**Comment by StollD** [comment]
Looks good to me, but the only problem I could see is that one route could return two different errors, but both have the same error code. The frontend would have to fall back to checking the error strings, which is what I would like to avoid.

I would certainly prefer the error code to be different per error message (so all "Modid is invalid" have the same code, and all "GameId is invalid" have the same code). Would that be ok for you?

Oh and: The `code` field should be an array, just like `reasons`

**Comment by morganpdx** [comment]
Ah ok.  Yeah sure, I'll change the codes by message, but try to keep them sort of in the same family if possible.  Maybe go to three digit codes, although that might get confusing with http status codes...four digit codes then? :)

**Comment by StollD** [comment]
It doesn't have to be an integer, so you could use anything... but four digit codes sounds good :)

**Comment by morganpdx** [comment]
Came across a couple of places where the returned error only has a single reason returned, instead of an array...I assume the code returned can be a single value as well in that case?  (see line 31 or 33 in endpoints/admin.py).  Also, in the case of lines 44-51 in endpoints/featured.py, I'm assuming you want another codes list to be included along with the errors list, correct?

**Comment by StollD** [comment]
I would prefer it to be an array, even if there is only one entry, just like the error messages.
Makes parsing them on the frontend much easier.

As for the error lists: Yes, a second list would be good, or alternatively, use tuples, and write a small function that constructs the final dictionary from that

**Comment by morganpdx** [comment]
coolio.  Should I then change the single reason instances to a single element array to match?  i.e. 

`return {'error': True, 'reason': 'Required fields are missing', 'codes': ['2510']}`
`return {'error': True, 'reason': ['Required fields are missing'], 'codes': ['2510']}`

I also noticed that there's a name change; from 'reasons' when it's an array to 'reason' in the above case.  Seems like it ought to be changed to allow for consistent error handling on the front end.

**Comment by StollD** [comment]
Are you looking at api.py?

That file is obsolete and was nuked in a recent PR 😄

**Comment by morganpdx** [comment]
Nope admin.py in endpoints, lines 31 and 33 both have it that way.

**Comment by StollD** [comment]
Good find! Yes, please change it

**Comment by morganpdx** [comment]
I'm creating a PR with the changes so far.  It's still in progress, but take a look at access.py - that's where I'm starting to change the return values to include the codes for the situations that already have multiple errors.  Not sure if that's the best approach, but initially it seemed that creating a function was a bit of overkill; but then I'm a bit unsure what is acceptable in the return value.  Plus my python is pretty new...  Any feedback is appreciated!

**Comment by morganpdx** [comment]
before I do that ☝️  which branch should i target with the PR?

**Comment by StollD** [comment]
master. And don't worry, as long as it works, we will merge it, and if it doesn't works we'll help you :)

**Comment by StollD** [comment]
Closing this, as @morganpdx resolved it in #16
