### ISSUE TITLE
Assuming String type for POST params

### ISSUE THREAD

**Issue by StollD** [KSP-SpaceDock/SpaceDock-Backend#17]
We do that currently, since `request.form` was all strings. Now, with JSON, we can differ between datatypes, and we should do that. That means removing all int / bool conversions and isdigit calls from POST params.

I would work on that, if noone wants to pick this up.

**Comment by sulami** [comment]
I'd be happy to pick this up

**Comment by StollD** [comment]
Sorry, should've noted that I already did it - #18 

Thank for the offer though
